### ISSUE TITLE
Nomes das classes geradas são complexos

### ISSUE THREAD

**Issue by robmachado** [nfephp-org/sped-console#9]
A nomenclatura das classes geradas pelo pacote são complexas como por exemplo inserindo "AType" em muitas classes e pastas. 

Por que é necessário esse "AType" ?
Esse "AType" pode ser retirado ?

**Comment by tonicospinelli** [comment]
o `AType` é o acronimo de `AnonymousType`, podemos criar uma classe de `NamingStrategy` para corrigir coisas deste tipo
